name: cross-node-test
nodes: [tst0, tst1, tst2, tst3, tst4, tst5]
tasks:
  - name: push cluster motd
    copy:
      src: files/motd.mustache
      dest: /etc/motd
      owner: root
      group: root
      mode: "0644"
