name: web-baseline

nodes:
  - tst0
  - tst1
  - tst4
  - tst5

tasks:
  - name: install curl
    install:
      packages: [curl]
      update_cache: true

  - name: clean up unused packages
    autoremove:
      purge: true
