#!/usr/bin/env bash
#
# Sets up the OpenStack command-line clients on the machine you run `orphera`
# from (scala0), OUTSIDE this repository:
#
#   ~/.venvs/openstack                  Python virtualenv with python-openstackclient
#   ~/.config/openstack/keystone-ca.crt the test CA that signed Keystone's certificate
#   ~/.config/openstack/admin-openrc.sh the credentials file (mode 600)
#
# Use it afterwards with:
#
#   source ~/.config/openstack/admin-openrc.sh
#   openstack token issue
#   openstack volume list
#
# Sourcing the rc file puts the venv first on PATH and sets the OS_* variables,
# and `deactivate-openstack` undoes both. Nothing here changes the repository,
# and the credentials are the project's hard-coded TEST values (see
# keystone_single_node.scala), not secrets.
#
# Safe to re-run: it upgrades the clients, refreshes the CA and rewrites the rc
# file. Override locations with VENV_DIR, CONF_DIR, KEYSTONE_HOST, CA_SSH_USER.
#
# Run from scala0:   utils/openstack-client-setup.sh

set -euo pipefail

VENV_DIR="${VENV_DIR:-$HOME/.venvs/openstack}"
CONF_DIR="${CONF_DIR:-$HOME/.config/openstack}"
KEYSTONE_HOST="${KEYSTONE_HOST:-tst6.ljalbinson.com}"
KEYSTONE_PORT="${KEYSTONE_PORT:-5000}"
CA_SSH_USER="${CA_SSH_USER:-localadmin}"
# Where keystone_single_node.scala leaves a world-readable copy of its test CA.
REMOTE_CA="/etc/kolla/keystone/ssl/ca.crt"

# Test-only credentials from keystone_single_node.scala (bootstrap admin).
ADMIN_USER="admin"
ADMIN_PASSWORD="orphera-test-keystone-admin-password"
ADMIN_PROJECT="admin"

CA_FILE="$CONF_DIR/keystone-ca.crt"
RC_FILE="$CONF_DIR/admin-openrc.sh"

log() { printf '[%s] %s\n' "$(date +%H:%M:%S)" "$1"; }
die() { printf 'ERROR: %s\n' "$1" >&2; exit 1; }

# ---- 1. virtualenv --------------------------------------------------------

command -v python3 >/dev/null 2>&1 || die "python3 is not installed"

if [ ! -x "$VENV_DIR/bin/python" ]; then
  log "creating virtualenv $VENV_DIR"
  mkdir -p "$(dirname "$VENV_DIR")"
  if ! python3 -m venv "$VENV_DIR" 2>/dev/null; then
    rm -rf "$VENV_DIR"
    die "python3 -m venv failed - on Ubuntu/Debian install it with: sudo apt-get install python3-venv"
  fi
else
  log "reusing virtualenv $VENV_DIR"
fi

log "installing python-openstackclient (this takes a minute)"
"$VENV_DIR/bin/python" -m pip install --quiet --upgrade pip
"$VENV_DIR/bin/python" -m pip install --quiet --upgrade python-openstackclient
log "installed: $("$VENV_DIR/bin/openstack" --version 2>&1)"

# ---- 2. Keystone's CA -----------------------------------------------------

mkdir -p "$CONF_DIR"
chmod 700 "$CONF_DIR"

fetch_ca_by_ssh() {
  ssh -o BatchMode=yes -o ConnectTimeout=10 "$CA_SSH_USER@$KEYSTONE_HOST" "cat $REMOTE_CA" 2>/dev/null
}

# Fallback: take the last certificate Keystone presents (it serves leaf + CA).
fetch_ca_by_tls() {
  command -v openssl >/dev/null 2>&1 || return 1
  echo | openssl s_client -connect "$KEYSTONE_HOST:$KEYSTONE_PORT" -servername "$KEYSTONE_HOST" -showcerts 2>/dev/null |
    awk '/-----BEGIN CERTIFICATE-----/{buf=""; keep=1} keep{buf=buf $0 "\n"} /-----END CERTIFICATE-----/{last=buf; keep=0} END{printf "%s", last}'
}

TMP_CA="$(mktemp)"
trap 'rm -f "$TMP_CA"' EXIT

if fetch_ca_by_ssh >"$TMP_CA" && grep -q 'BEGIN CERTIFICATE' "$TMP_CA"; then
  log "fetched the CA from $KEYSTONE_HOST over ssh"
elif fetch_ca_by_tls >"$TMP_CA" && grep -q 'BEGIN CERTIFICATE' "$TMP_CA"; then
  log "ssh failed; took the CA from Keystone's TLS handshake (trust on first use)"
else
  die "could not get Keystone's CA from $KEYSTONE_HOST (ssh and TLS both failed) - is keystone_single_node.scala applied and the host resolvable?"
fi

if ! openssl x509 -in "$TMP_CA" -noout -subject >/dev/null 2>&1; then
  die "what was fetched is not a valid certificate"
fi
install -m 644 "$TMP_CA" "$CA_FILE"
log "CA saved to $CA_FILE ($(openssl x509 -in "$CA_FILE" -noout -subject))"

# ---- 3. rc file -----------------------------------------------------------

umask 077
cat >"$RC_FILE" <<RC
# OpenStack admin credentials for the Orphera test fleet.
# Source this file:   source $RC_FILE
# Generated by utils/openstack-client-setup.sh - re-run that script to refresh.

if [ -z "\${_ORPHERA_OS_OLD_PATH+x}" ]; then
  export _ORPHERA_OS_OLD_PATH="\$PATH"
  export PATH="$VENV_DIR/bin:\$PATH"
fi

export OS_AUTH_URL="https://$KEYSTONE_HOST:$KEYSTONE_PORT/v3"
export OS_IDENTITY_API_VERSION=3
export OS_VOLUME_API_VERSION=3
export OS_INTERFACE=public
export OS_REGION_NAME=RegionOne
export OS_AUTH_TYPE=password
export OS_USERNAME="$ADMIN_USER"
export OS_PASSWORD="$ADMIN_PASSWORD"
export OS_PROJECT_NAME="$ADMIN_PROJECT"
export OS_USER_DOMAIN_NAME=Default
export OS_PROJECT_DOMAIN_NAME=Default
export OS_CACERT="$CA_FILE"

# Undo: removes the venv from PATH and unsets every OS_* variable set above.
deactivate-openstack() {
  if [ -n "\${_ORPHERA_OS_OLD_PATH+x}" ]; then
    export PATH="\$_ORPHERA_OS_OLD_PATH"
    unset _ORPHERA_OS_OLD_PATH
  fi
  unset OS_AUTH_URL OS_IDENTITY_API_VERSION OS_VOLUME_API_VERSION OS_INTERFACE \\
    OS_REGION_NAME OS_AUTH_TYPE OS_USERNAME OS_PASSWORD OS_PROJECT_NAME \\
    OS_USER_DOMAIN_NAME OS_PROJECT_DOMAIN_NAME OS_CACERT
  unset -f deactivate-openstack
}
RC
chmod 600 "$RC_FILE"
log "wrote $RC_FILE"

# ---- 4. prove it works ----------------------------------------------------

log "checking: issuing a token against Keystone"
# Run in a subshell so this script's own environment stays clean.
if (
  # shellcheck disable=SC1090
  source "$RC_FILE"
  openstack token issue -f value -c project_id >/dev/null
); then
  log "OK - the clients can authenticate"
else
  die "token request failed - check that tst6 resolves from here, Keystone is up, and the CA matches"
fi

cat <<EOF

Done. To use it in a shell:

  source $RC_FILE
  openstack token issue
  openstack service list
  openstack endpoint list
  openstack volume service list
  openstack volume create --size 1 test && openstack volume list

Leave with:  deactivate-openstack
EOF
